FROM calculator

COPY tests tests
ENV NODE_ENV dev

RUN npm update && \
    npm install -g mocha && \
    npm install supertest --save-dev

CMD ["mocha", "tests/test.js", "--reporter", "spec", "supertest"]
